# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l8O9-nrXTXmgs5i5is7KTmQjUwBhB9sP
"""

import pandas as pd

import matplotlib.pyplot as plt

import geopandas as gpd

import folium

from folium.plugins import HeatMap

data = pd.read_csv('traffic_data.csv')

print(data.columns)

accident_counts = data['Location'].value_counts()

plt.figure(figsize=(10, 6))

accident_counts.plot(kind='bar')

plt.title('Accident Counts by Location')

plt.xlabel('Location')

plt.ylabel('Number of Accidents')

plt.show()

gdf=gpd.GeoDataFrame(data, geometry=gpd.points_from_xy(data.Longitude, data.Latitude))

m=folium.Map(location=[data.Latitude.mean(), data.Longitude.mean()], zoom_start=12)

HeatMap(data[['Latitude', 'Longitude']].values).add_to(m)

m.save('heatmap.html')