# -*- coding: utf-8 -*-
"""testing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1Ya2Zk2TKUYW7TCdxDEb8vnajypzdgS
"""

import unittest
import pandas as pd
import geopandas as gpd
from folium import Map
from folium.plugins import HeatMap

class TestTrafficAnalysis(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Mock dataset similar to traffic_data.csv
        cls.data = pd.DataFrame({
            'Location': ['Main Street', 'Downtown Avenue', 'Main Street', 'Elmwood Road'],
            'Latitude': [40.7128, 34.0522, 40.7128, 41.8781],
            'Longitude': [-74.0060, -118.2437, -74.0060, -87.6298]
        })

    def test_data_loading(self):
        self.assertEqual(len(self.data), 4)
        self.assertIn('Location', self.data.columns)

    def test_accident_counts(self):
        accident_counts = self.data['Location'].value_counts()
        self.assertEqual(accident_counts['Main Street'], 2)
        self.assertEqual(accident_counts['Downtown Avenue'], 1)

    def test_geodataframe_creation(self):
        gdf = gpd.GeoDataFrame(
            self.data, geometry=gpd.points_from_xy(self.data.Longitude, self.data.Latitude)
        )
        self.assertEqual(len(gdf), 4)
        self.assertIn('geometry', gdf.columns)

    def test_heatmap_creation(self):
        m = Map(location=[self.data.Latitude.mean(), self.data.Longitude.mean()], zoom_start=12)
        try:
            HeatMap(self.data[['Latitude', 'Longitude']].values).add_to(m)
            map_created = True
        except Exception:
            map_created = False
        self.assertTrue(map_created)

if __name__ == "__main__":
    unittest.main(argv=[''], exit=False)